// In this file you can specify the trial data for your experiment


const practice_trials = {
    key_press: [
      {
          picture: "images/practice/1_50_same.jpg",
          pic_num: 1,
          expected: "same",
          rot_deg: 50,
          key1: "f",
          key2: "j",
          f: "same",
          j: "different",

      },
      {
          picture: "images/practice/1_50_different.jpg",
          pic_num: 1,
          expected: "different",
          rot_deg: 50,
          key1: "f",
          key2: "j",
          f: "same",
          j: "different",

      },
      {
          picture: "images/practice/1_150_same.jpg",
          pic_num: 1,
          expected: "same",
          rot_deg: 150,
          key1: "f",
          key2: "j",
          f: "same",
          j: "different",
      },
      {
          picture: "images/practice/1_150_different.jpg",
          pic_num: 1,
          expected: "different",
          rot_deg: 150,
          key1: "f",
          key2: "j",
          f: "same",
          j: "different",
      },
      {
          picture: "images/practice/2_50_same.jpg",
          pic_num: 2,
          expected: "same",
          rot_deg: 50,
          key1: "f",
          key2: "j",
          f: "same",
          j: "different",
      },
      {
          picture: "images/practice/2_50_different.jpg",
          pic_num: 2,
          expected: "different",
          rot_deg: 50,
          key1: "f",
          key2: "j",
          f: "same",
          j: "different",
      },
      {
          picture: "images/practice/2_150_same.jpg",
          pic_num: 2,
          expected: "same",
          rot_deg: 150,
          key1: "f",
          key2: "j",
          f: "same",
          j: "different",
      },
      {
          picture: "images/practice/2_150_different.jpg",
          pic_num: 2,
          expected: "different",
          rot_deg: 150,
          key1: "f",
          key2: "j",
          f: "same",
          j: "different",
      },

      {
          picture: "images/practice/3_50_same.jpg",
          pic_num: 3,
          expected: "same",
          rot_deg: 50,
          key1: "f",
          key2: "j",
          f: "same",
          j: "different",
      },
      {
          picture: "images/practice/3_50_different.jpg",
          pic_num: 3,
          expected: "different",
          rot_deg: 50,
          key1: "f",
          key2: "j",
          f: "same",
          j: "different",
      },
      {
          picture: "images/practice/3_150_same.jpg",
          pic_num: 3,
          expected: "same",
          rot_deg: 150,
          key1: "f",
          key2: "j",
          f: "same",
          j: "different",
      },
      {
          picture: "images/practice/3_150_different.jpg",
          pic_num: 3,
          expected: "different",
          rot_deg: 150,
          key1: "f",
          key2: "j",
          f: "same",
          j: "different",
      },
    ],
};

const main_trials = {
    key_press: [
        {
            picture: "images/main/4_50_same.jpg",
            pic_num: 4,
            expected: "same",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/4_50_different.jpg",
            pic_num: 4,
            expected: "different",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/4_150_same.jpg",
            pic_num: 4,
            expected: "same",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/4_150_different.jpg",
            pic_num: 4,
            expected: "different",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },

        {
            picture: "images/main/5_50_same.jpg",
            pic_num: 5,
            expected: "same",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/5_50_different.jpg",
            pic_num: 5,
            expected: "different",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/5_150_same.jpg",
            pic_num: 5,
            expected: "same",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/5_150_different.jpg",
            pic_num: 5,
            expected: "different",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/6_50_same.jpg",
            pic_num: 6,
            expected: "same",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/6_50_different.jpg",
            pic_num: 6,
            expected: "different",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/6_150_same.jpg",
            pic_num: 6,
            expected: "same",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/6_150_different.jpg",
            pic_num: 6,
            expected: "different",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },

        {
            picture: "images/main/7_50_same.jpg",
            pic_num: 7,
            expected: "same",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/7_50_different.jpg",
            pic_num: 7,
            expected: "different",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/7_150_same.jpg",
            pic_num: 7,
            expected: "same",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/7_150_different.jpg",
            pic_num: 7,
            expected: "different",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },

        {
            picture: "images/main/8_50_same.jpg",
            pic_num: 8,
            expected: "same",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/8_50_different.jpg",
            pic_num: 8,
            expected: "different",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/8_150_same.jpg",
            pic_num: 8,
            expected: "same",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/8_150_different.jpg",
            pic_num: 8,
            expected: "different",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },

        {
            picture: "images/main/9_50_same.jpg",
            pic_num: 9,
            expected: "same",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/9_50_different.jpg",
            pic_num: 9,
            expected: "different",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/9_150_same.jpg",
            pic_num: 9,
            expected: "same",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/9_150_different.jpg",
            pic_num: 9,
            expected: "different",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/10_50_same.jpg",
            pic_num: 10,
            expected: "same",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/10_50_different.jpg",
            pic_num: 10,
            expected: "different",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/10_150_same.jpg",
            pic_num: 10,
            expected: "same",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/10_150_different.jpg",
            pic_num: 10,
            expected: "different",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/11_50_same.jpg",
            pic_num: 11,
            expected: "same",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/11_50_different.jpg",
            pic_num: 11,
            expected: "different",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/11_150_same.jpg",
            pic_num: 11,
            expected: "same",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/11_150_different.jpg",
            pic_num: 11,
            expected: "different",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/12_50_same.jpg",
            pic_num: 12,
            expected: "same",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/12_50_different.jpg",
            pic_num: 12,
            expected: "different",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/12_150_same.jpg",
            pic_num: 12,
            expected: "same",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/12_150_different.jpg",
            pic_num: 12,
            expected: "different",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/13_50_same.jpg",
            pic_num: 13,
            expected: "same",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/13_50_different.jpg",
            pic_num: 13,
            expected: "different",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/13_150_same.jpg",
            pic_num: 13,
            expected: "same",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/13_150_different.jpg",
            pic_num: 13,
            expected: "different",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/14_50_same.jpg",
            pic_num: 14,
            expected: "same",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/14_50_different.jpg",
            pic_num: 14,
            expected: "different",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/14_150_same.jpg",
            pic_num: 14,
            expected: "same",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/14_150_different.jpg",
            pic_num: 14,
            expected: "different",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/15_50_same.jpg",
            pic_num: 15,
            expected: "same",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/15_50_different.jpg",
            pic_num: 15,
            expected: "different",
            rot_deg: 50,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/15_150_same.jpg",
            pic_num: 15,
            expected: "same",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
        {
            picture: "images/main/15_150_different.jpg",
            pic_num: 15,
            expected: "different",
            rot_deg: 150,
            key1: "f",
            key2: "j",
            f: "same",
            j: "different",
        },
    ],
};
